### ISSUE TITLE
TODO from Kadaster

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/3dfier#15]
**Trekker Kadaster**
- [x] Klassificiatie vegetatie (Trekker BertJan)
- [x] Vergelijking input: AHN3 versus point cloud (PC):
- [x] 3DBGT-AHN3
- [x] 3DBGT-PC interpolated
- [x] 3DBGT-PC non interpolated
- [x] FME workflow om voor conversie van 3Dfier OBJ met object id’s naar benodigde input voor Kadaster visualisatie workflow en eventueel CityGML
- [x] Uitzoeken uitvoer/opslag formaat
- [x] Opschalen naar Nederland
- [ ] Onderzoek naar aansluiten BGT LOD0 voor combinatie met LOD2 BAG Panden
- [x] test p(p)repair for fixing BGT (prepair: https://github.com/tudelft3d/prepair/releases/tag/v0.7.1)
- [x] Controleren of aangrenzende polygonen van aanliggende tiles goed aansluiten in hoogte
- [x] Configuratie van LAS classes in YAML per object klasse nalopen

**Trekker TUDelft**
- [x] fix the bug with buildings not connected to ground in CityGML output -> triangulate buildings
- [x] Make the roads outlier detection angle configurable
- [x] Merge and clean current branches and make release v1.0 RC1
- [x] Create PostGIS-IMGeo output
- [x] Error handling TIN greedy insertion code
- [x] Testing of road outlier filtering
- [x] multiple outputs --> tclap
- [x] compile p(p)repair for Windows
- [x] Make the roads "flatter" and less bumpy with outlier detection
- [x] Verbeteren van de implementatie voor bruggen en overpassen
- [x] Stabiele versie waarmee Kadaster vergelijking kan uitvoeren
- [x] Update van Readme en input parameter beschrijving
- [x] Controleren welke waarde gebouwen krijgen waarvoor geen hoogte is gevonden
- [x] Segmentation Fault (core dumped) in CDT voor grote hoeveelheid punten
- [x] Uitwerken van LOD0 functie, gebouwen met alleen vloeren
- [x] Uitwerken van LOD1 functie, gebouwen als solids
- [x] 3D IMGeo specificaties verfijnen, verbeteren, aanvullen
- [x] Onderzoeken van belangen in verschillende attribuutdata binnen eenzelfde klasse (bijv. wegdek, parkeerplaats, parkeerdek en bijv basin in OverigeBouwwerken)
- [x] Testen op fouten in waterdichtheid van modellen
- [x] Output naar CityGML

**Whishlist**
- [x] Excluding of LAS classes in YAML besides including

**Comment by TonyBaving** [comment]
Test
